version: "3"
services:
  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_stored:/data
    ports:
      - "6379:6379"
    networks:
      - moviemanagementnet

volumes:
  redis_stored: {}

networks:
  moviemanagementnet:
    external: true
