version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    container_name: elastic-container
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    # restart: always
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - moviemanagementnet
  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-container:9200
    ports:
      - "5601:5601"
    networks:
      - moviemanagementnet
    depends_on:
      - elasticsearch
volumes:
  data: {}

networks:
  moviemanagementnet:
    external: true
