version: "3"
services:
  consul:
    container_name: consul
    image: hashicorp/consul:1.11.2
    volumes:
      - consul:/consul/data
      #https://developer.hashicorp.com/consul/docs/agent/config/config-files
      - ./config.json:/consul/config/config.json
    networks:
      - moviemanagementnet
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 1"

volumes:
  consul: {}

networks:
  moviemanagementnet:
    external: true
