version: "3"
services:
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: pa55w0rd!
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - moviemanagementnet

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      MONGO_CONFIG_MONGODB_ADMINUSER: sa
      MONGO_CONFIG_MONGODB_ADMINPASSWORD: pa55w0rd!
      ME_CONFIG_MONGODB_URL: mongodb://sa:pa55w0rd!@mongo:27017
    ports:
      - "8081:8081"
    networks:
      - moviemanagementnet

networks:
  moviemanagementnet:
    external: true

volumes:
  mongodb: {}
