version: "3"
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - data:/var/lib/rabbitmq/
    networks:
      - moviemanagementnet

volumes:
  data: {}

networks:
  moviemanagementnet:
    external: true
