_format_version: "3.0"
_transform: true

services:
  - name: user-api
    url: docker.internal.host:5000/api/user
    plugins:
      - name: rbac_jwt
        config:
          jwk_stored_url: docker.internal.host:5000/api/.well-knowns
          rbac_server: sql
          rbac_database: AuthServer
          rbac_database_user: sa
          rbac_database_password: pa55w0rd!
    routes:
      - name: user-api-router
        paths:
          - /api/user

  - name: auth-api
    url: docker.internal.host:5000/api/auth
    routes:
      - name: auth-api-router
        paths:
          - /api/auth

  - name: admin-api
    url: docker.internal.host:5000/api/admin
    routes:
      - name: admin-api-router
        paths:
          - /api/admin

  - name: role-api
    url: docker.internal.host:5000/api/role
    routes:
      - name: role-api-router
        paths:
          - /api/role

  - name: permission-api
    url: docker.internal.host:5000/api/permission
    routes:
      - name: permission-api-router
        paths:
          - /api/permission

  - name: operation-api
    url: docker.internal.host:5000/api/operation
    routes:
      - name: operation-api-router
        paths:
          - /api/operation

  - name: jwk-api
    url: docker.internal.host:5000/api/.well-knowns
    routes:
      - name: jwk-api-router
        paths:
          - /api/.well-knowns
