version: "3"
services:
  authserver:
    container_name: authserver
    build: ./../../AuthServer/AuthServer.API
    environment:
      ASPNETCORE_URLS: "http://+:5000"
    ports:
      - "5000:5000"
    networks:
      - moviemanagementnet

networks:
  moviemanagementnet:
    external: true
